%YAML:1.0
#Data info
##dataset wuhan GI
PointFilepathOrigin: "H:/1_P2M_Robust_Test/4_Wuhan_gaojia/pc"
PointFilepathRefine: "H:/2_P2M_Robust_Test_Result/4_Wuhan_gaojia/finePointClouds_result"
TrajectoryFile: "H:/2_P2M_Robust_Test_Result/4_Wuhan_gaojia/traj_xyz.traj"

#dataset shanghai
#PointFilepathOrigin: "F:/Data/Zhangjiang8Block/outPC/origin"
#PointFilepathRefine: "F:/Data/Zhangjiang8Block/outPC/refine"
#osg roam only need a few of view points which is different from others
#TrajectoryFile: "F:/Data/Zhangjiang8Block/outPC/small-trajfile.traj"

#dataset shanghai alienware
#PointFilepathOrigin: "D:/data/shanghai/1km2/roam/origin"
#PointFilepathRefine: "D:/data/shanghai/1km2/roam/refine"
#osg roam only need a few of view points which is different from others
#TrajectoryFile: "D:/data/shanghai/1km2/roam/1km2.traj"

#dataset Shanghai
#PointFilepathOrigin: "F:/Data/Zhangjiang8Block/outPC/origin"
#PointFilepathRefine: "F:/Data/Zhangjiang8Block/outPC/refine"
#osg roam only need a few of view points which is different from others
#TrajectoryFile: "F:/Data/Zhangjiang8Block/outPC/small-trajfile.traj"
#TrajectoryFile: "D:/data/Estonia/roam/20200309/20200312Display/Estonia-20200312Display.traj"

#Roam view Info

#The osg coordinate definition as left-hand coordinate which is right-front-up(x-y-z) and 
#the OpenGL coordinate definition also as left-hand coordinate which is right-up-behind(x-y-z), z axis is pointer to outside the screen
#Initial viewport is along down direction, so heading is rotate to along the y positive direction, rotate axis is x axis 

#y point to the trajectory direction, -z point to down view, y-down-45 point to y axis and 45 degree
ViewportDirection: "y"
#speed is  //larger ==> slower
RoamSpeed: 0.5
OpenPerspective: 1

#Shape Info
OpenShpWindow: "false"
ShapeFilepath: "D:/data/Estonia/roam/20200309/20200312Display/traj_block_shps_0/Trajectory0.shp"
